### ISSUE TITLE
ImportError: cannot import name '_validate_lengths'

### ISSUE THREAD

**Issue by xaionaro** [lauramanduchi/CIL2018#13]
```
xaionaro@alien:~/public/CIL2018$ python3 ./produce_images.py 
Traceback (most recent call last):
  File "./produce_images.py", line 5, in <module>
    from skimage import io
  File "/usr/lib/python3/dist-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/usr/lib/python3/dist-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/usr/lib/python3/dist-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```

**Comment by JustForCodin** [comment]
Still no solution?
